### PR TITLE
fix: `MdbxStorageCursor` non first key issue

### LINKED ISSUE #600: MdbxStorageCursor `next()` fails for non-first key unless `seek()` is called
### Describe the bug

`MdbxStorageCursor` / `MdbxTrieCursor` iteration depends on an explicit `seek()` call.

Given dup-sorted data:

* `(hashed_address=0x01, slot=0x11)`
* `(hashed_address=0x02, slot=0x12)`

If a cursor is constructed for `hashed_address=0x02` and iteration starts with `next()`, it returns `None` (no rows).
But if `seek(hashed_address)` is called first, then `next()` returns the expected row.

**Expected:** cursor constructed for a key should return the first row for that key on `next()` without requiring a manual `seek()`.
**Actual:** `next()` yields nothing unless `seek()` was called, and this only shows up when the key is not the first key in the table.

This breaks consumers that assume “cursor-for-key is ready to iterate” semantics.

### Steps to reproduce

Described above

### Node logs

```text

```

### Platform(s)

_No response_

### Container Type

Not running in a container

### What version/commit are you on?

unstable

### What database version are you on?

---

### Which chain / network are you on?

---

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

_No response_

### If you've built Reth from source, provide the full command you used

_No response_

### Code of Conduct

- [x] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by itschaindev**
Closes #600

### CODE REVIEW

File: crates/optimism/trie/src/db/cursor.rs [hunk 1]
```diff
@@ -43,6 +43,11 @@ where
         Self { _table: PhantomData, cursor, max_block_number }
     }
 
+    /// Check if the cursor is currently positioned at a valid row.
+    fn is_positioned(&mut self) -> OpProofsStorageResult<bool> {
+        Ok(self.cursor.current()?.is_some())
```
Comment (sadiq1971) [inline crates/optimism/trie/src/db/cursor.rs:48]: Will it fetch from the database?

File: crates/optimism/trie/src/db/cursor.rs [hunk 2]
```diff
@@ -308,6 +313,15 @@ where
     }
 
     fn next(&mut self) -> Result<Option<(B256, Self::Value)>, DatabaseError> {
+        // If the cursor is not positioned, we need to seek to the first key for our bound address
```
Comment (sadiq1971) [inline crates/optimism/trie/src/db/cursor.rs:325]: Need to do same for StorageTrie.

File: crates/optimism/trie/src/db/cursor.rs (hunk 1 above)
Comment (itschaindev) [reply crates/optimism/trie/src/db/cursor.rs:48]: Nope. It returns cursor's current position from memory. Its a fast check to decide before performing more expensive operation `seek()`

File: crates/optimism/trie/src/db/cursor.rs (hunk 2 above)
Comment (itschaindev) [reply crates/optimism/trie/src/db/cursor.rs:325]: @sadiq1971 Do you mean `MdbxTrieCursor<StorageTrieHistory, Cursor>`?

Comment (sadiq1971) [reply crates/optimism/trie/src/db/cursor.rs:325]: Yes

**Review by sadiq1971 — APPROVED** [review]

**Review by dhyaniarun1993 — APPROVED** [review]
lgtm
